---
title: "My English Activity Log : MEAL"
author:
  - name: "Pinchon Audrey" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---

Here is a short description of my activities during the year for the English course.

- Sept. 21st: I had my first English lesson at the university. 

- Sept. 25th : I downloaded the BBC Application on my phone. 

- Oct. 15th : I downloaded Tandem on my phone. This app allows you to learn languages by speaking with people all over the world.

- Nov. 1st: This weekend, I work on my English Grammar exercises. I did exercises of present perfect simple and past perfect simple. I want to improve my English. I also did research for my topic. I analyzed and published an article this Sunday.

- Nov. 7th : I learned and studied new vocabulary words. I analyzed and published a new article on breast cancer.

- Nov. 20th : Today, I learned new vocabulary words while studying Unit 3. I praticed my vocabulary on quizlet. I did my comparative and superlative exercises. I also started watching a series in English "Get Even".

- Nov. 21st : Today, I analyzed and published my 4th article on breast cancer on my blog. This article talks about the effect of bee venom on breast cancer cells.

- Dec. 2nd  : I started a new series : "Superstition". This series tells the story of a family funeral business that is linked to the supernatural world. This business deals with the dead but also with people who have died in an unexplained way.

- Dec. 8th : I finished "Superstition" because it's a short series, one season only.  

- Dec. 9th : This morning, I worked on my English grammar, mainly theory and irregular verbs. Then I started "Biohackers" with English subtitles because I would like to improve my listening comprehension, ... 

